#!/usr/bin/env python3
"""
PRP Generator Script

This script generates Project Research Papers (PRPs) for tasks during the Planning phase.
PRPs provide comprehensive documentation and context for task execution.
"""

import argparse
import os
import sys
from datetime import datetime
from pathlib import Path
from typing import Optional


def create_prp_content(
    task_id: str,
    project_id: str,
    title: str,
    description: str,
    worktree_path: str
) -> str:
    """Generate the PRP content for a task."""
    
    current_time = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    
    # Basic PRP template
    prp_content = f"""# PRP: {title}

## Task Overview
- **Task ID**: {task_id}
- **Project ID**: {project_id}
- **Status**: Planning
- **Generated**: {current_time}

## Description
{description if description else "No description provided"}

## Context Analysis

### Codebase Structure
The task is being executed in the following context:
- **Worktree Path**: {worktree_path}
- **Current Directory**: {os.getcwd()}

### Implementation Planning

#### Phase 1: Research & Analysis
- [ ] Analyze existing codebase patterns
- [ ] Identify similar implementations
- [ ] Review API documentation
- [ ] Understand data flow requirements

#### Phase 2: Design & Architecture
- [ ] Design component/module structure
- [ ] Plan API interfaces
- [ ] Consider error handling strategies
- [ ] Plan testing approach

#### Phase 3: Implementation
- [ ] Implement core functionality
- [ ] Add error handling
- [ ] Write comprehensive tests
- [ ] Document implementation

#### Phase 4: Testing & Validation
- [ ] Unit tests
- [ ] Integration tests
- [ ] Manual testing
- [ ] Performance validation

#### Phase 5: Documentation & Finalization
- [ ] Update documentation
- [ ] Code review
- [ ] Final validation
- [ ] Deployment preparation

## Technical Considerations

### Dependencies
- Review existing dependencies in the project
- Consider if new dependencies are needed
- Ensure compatibility with existing stack

### Security Considerations
- Input validation requirements
- Authentication/authorization needs
- Data sanitization requirements

### Performance Considerations
- Expected load/usage patterns
- Optimization opportunities
- Resource usage implications

## Success Criteria
- [ ] All planned functionality implemented
- [ ] All tests passing
- [ ] Documentation updated
- [ ] Performance requirements met
- [ ] Security requirements addressed

## Next Steps
1. Move task to InProgress state
2. Begin implementation following this plan
3. Update this PRP with findings during implementation
4. Complete implementation and move to InReview

## Notes
This PRP was generated automatically during the Planning phase. 
It should be updated with specific findings and decisions made during implementation.

---
*Generated by PRP Generator v1.0*
"""
    
    return prp_content


def generate_prp(
    task_id: str,
    project_id: str,
    title: str,
    description: str,
    output_dir: str,
    worktree_path: str
) -> None:
    """Generate a PRP file for the given task."""
    
    print(f"[PRP] Starting PRP generation for task: {title}")
    print(f"[PRP] Task ID: {task_id}")
    print(f"[PRP] Project ID: {project_id}")
    
    # Create output directory
    output_path = Path(output_dir)
    output_path.mkdir(parents=True, exist_ok=True)
    
    # Generate PRP content
    prp_content = create_prp_content(
        task_id=task_id,
        project_id=project_id,
        title=title,
        description=description,
        worktree_path=worktree_path
    )
    
    # Write PRP file
    prp_file_path = output_path / "prp.md"
    with open(prp_file_path, "w", encoding="utf-8") as f:
        f.write(prp_content)
    
    print(f"[PRP] PRP generation completed successfully")
    print(f"[PRP] Generated file: {prp_file_path}")
    print(f"[PRP] Task ready for transition to InProgress state")


def main() -> None:
    """Main entry point for the PRP generator."""
    
    parser = argparse.ArgumentParser(
        description="Generate Project Research Papers (PRPs) for tasks"
    )
    parser.add_argument(
        "--task-id",
        required=True,
        help="The UUID of the task"
    )
    parser.add_argument(
        "--project-id",
        required=True,
        help="The UUID of the project"
    )
    parser.add_argument(
        "--title",
        required=True,
        help="The title of the task"
    )
    parser.add_argument(
        "--description",
        default="",
        help="The description of the task"
    )
    parser.add_argument(
        "--output-dir",
        required=True,
        help="The directory to write the PRP file"
    )
    parser.add_argument(
        "--worktree-path",
        default=".",
        help="The path to the worktree"
    )
    
    args = parser.parse_args()
    
    try:
        generate_prp(
            task_id=args.task_id,
            project_id=args.project_id,
            title=args.title,
            description=args.description,
            output_dir=args.output_dir,
            worktree_path=args.worktree_path
        )
    except Exception as e:
        print(f"[PRP] Error generating PRP: {e}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()